### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by abalkin** [abalkin/pytest-leaks#16]
Let's plan the 0.3 release here. @pv and @seberg - please send me your PyPI user names so that I can add you as maintainers there.

**Comment by seberg** [comment]
Thanks, I honestly do not have one at this time. But could create one or are you fine @pv?

**Comment by abalkin** [comment]
Who would like to volunteer to be a release manager?

**Comment by abalkin** [comment]
I usually try to set up my projects so that PyPI uploads are automatically triggered after Github releases.  I am not sure where we are in this project.

**Comment by pv** [comment]
I'm [pv](https://pypi.org/user/pv/) also on PyPi. I think currently the authentication options offered by PyPi are not good enough (per-project deployment keys) for automatic uploads on my account. Regardless, I can RM this release, if you don't volunteer.

The current pytest-leaks master branch I guess is more or less in a releasable state. There are some things that could be nice to have (eg #17 which is relevant also for numpy, etc), but those can be done later.

**Comment by abalkin** [comment]
@pv – I am here to help, but you are in a better position to decide what should go into the release.

**Comment by abalkin** [comment]
@pv - I made you a co-owner on PyPI.  This way you will be able to add a "maintainer" account that can be used by CI.

**Comment by abalkin** [comment]
I suggest making a manual release now and start working on automation for the 0.3.1 release.

**Comment by pv** [comment]
Yes, that sounds best. I'm planning to do some real-world checking on the current status, but if that turns out ok, I think I'll release 0.3.0 as it is now soon.

**Comment by pv** [comment]
Released.

Of course, forgot to update `__version__` in `__init__.py`, but that shouldn't matter in practice. For next release, we should make setup.py pick the version number from `__init__.py` (or vice versa) so it's not duplicated in two places.
