### ISSUE TITLE
fname parameter that defaults to reflog.txt doesn't seem to be implemented

### ISSUE THREAD

**Issue by dam5h** [abalkin/pytest-leaks#5]
Hello,

Trying this package today for the first time.  I can't seem to get access to the report at `reflog.txt` that is mentioned in the help docs.  Is this stale documentation?  I am looking for more information on the Leaks and Blocks instances reported in the console.

Thanks,
Dave

**Comment by abalkin** [comment]
Writing to `reflog.txt` is not supported.  The documentation you see was copied from `python -mtest --help` and should be corrected.
